language: python
python:
  - "2.7"
install:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
# command to run tests
script: 
  - python Server/guessWhat_test.py


notifications:
  email: false